### ISSUE TITLE
Using two different options causes a timeout

### ISSUE THREAD

**Issue by utsysadmin** [operable/cog#1401]
If I use two different options it causes a timeout to occur.  If I use the same option twice it overrides the first option instead of creating a list valued option.  If I use just one option it will execute my wrapper script but won't have enough arguments to run it.

Config.yml
```
options:
      env:
        type: string
        required: true
        description: environment
        short_flag: e
      apps:
        type: string
        required: false
        description: apps
        short_flag: a
```

cog log:
```
2017-09-19T17:20:22.963 [error] ** State machine #PID<0.9208.0> terminating 
** Last message in was {:EXIT, #PID<0.9207.0>, {:handler, %RuntimeError{message: ":timeout"}}}
** When State == :connected
**      Data  == {:state, #PID<0.9207.0>, '<0.9208.0>', {0, 0, 0, 0}, 1883, #Port<0.58406>,
 #PID<0.9209.0>,
 {:proto_state, #Port<0.58406>, '127.0.0.1:43087', 4, "MQTT",
  "emqttc_cog_7b077107ab8a3d99952b", true, 90, false,
  {:mqtt_message, 0, false, false, :undefined, :undefined, :undefined},
  "COG_INTERNAL",
  "JTZmScHGKY6Yj3rkAPsBE2UeNhOsHT1Ijyr3vPAZVwklVI2f+Y2NBI8kRmuc8lNp", 35,
  %{"bot/chat/adapter" => 1, "bot/chat/adapter/incoming" => 1}, %{}, %{}, %{},
  {:gen_logger, :lager_logger, 8}},
 [{#PID<0.9207.0>, #Reference<0.0.262145.220222>}],
 %{"bot/chat/adapter" => {1, [#PID<0.9207.0>]},
   "bot/chat/adapter/incoming" => {1, [#PID<0.9207.0>]}}, [], [], %{}, 2, false,
 {:keepalive, #Port<0.58406>, :send_oct, 7509, 90, {:keepalive, :timeout},
  #Reference<0.0.2.88168>}, 90, 60, 4, 8, :undefined, :tcp, :undefined,
 {:gen_logger, :lager_logger, 8}, [], []}
** Reason for termination = 
** {:handler, %RuntimeError{message: ":timeout"}}
```

I believe the pipeline is failing at some point but not letting me know at what point.  I added some STDOUT debugging to my wrapper script so I know wither it's being called but before that I was getting `Pipeline executed successfully, but no output was returned`
