### ISSUE TITLE
Cog bundle deploy endpoint

### ISSUE THREAD

**Issue by mpeck** [operable/cog#490]
# Motivation
go-relay will follow a different pattern than our current implementation of relay. Instead of installing bundles on relays directly, a user will upload a config file to Cog and Cog will push the config to the proper relays. To support this, we need an endpoint to upload deployment configs too.

# Objective
To have an endpoint that accepts a file in `yaml` or `json` format. Cog will parse the file store the appropriate data. Pushing that data to relay will happen in a follow up issue.

# Research
Updates to both spanner and Cog will be required. We need to add an endpoint, `POST` `v1/bundles/deploy`, that accepts a config file in yaml or json. And update config's JSONSchema in spanner to validate and parse said config file. Since a format version will be included with the config we could have spanner dynamically choose the proper format to validate. Though that may be out of scope for this issue, keep it in mind. Lastly we need to add that config data to the db.

Config files will look as follows:
```
# Format version
cog_bundle_version: 2

name: <string>
version: <semver string>
type: <simple or docker>
permissions: <list of strings>

# Required only if type == docker
docker:
  image: <name or image id>
  tag: <string, optional>
commands:
  <command_name>:
    executable: <string>
    options: <hash of option defs>
    rules: <list of rules>
    default_env: <hash of env vars>
  <command_name>:
    executable: <string>
    options: <hash of option defs>
    rules: <list of rules>
    default_env: <hash of env vars>
templates:
  - <template_name>
      provider: <slack or hipchat>
      contents: <literal template contents>
  - <template_name>
      provider: <slack or hipchat>
      contents: <literal template contents>
```

# Questions
*  Do we need type? Or could we introspect based on the presence of the docker key?
  ** The endpoint will require type to be set for possible future type. cogctl can fill it in for the user automatically for now though.
*  When a new config is uploaded that references the same bundle with the same version, do we overwrite or error? I think that should be an error case.
  ** The user should get an error if they upload a conflicting version.

# Plan
- [x] Update spanner to properly parse and validate bundle configs
- [x] Add the REST endpoint to Cog
- [x] Persist config data
