### ISSUE TITLE
cogctl bundles deploy

### ISSUE THREAD

**Issue by mpeck** [operable/cog#491]
# Motivation
With the changes to relay, Cog will be responsible for managing bundle configs. In order to make it as easy as possible for users to create and upload bundle configs to Cog.

# Objective
cogctl will have a new bundles subcommand `deploy`. This command will provide tooling necessary to make uploading configs to Cog as easy as possible.

# Research
## Subcommand details
`cogctl bundles deploy [--templates=path/to/templates] path/to/config.yaml`

The config file format will be as follows:
```
# Format version
cog_bundle_version: 2

name: <string>
version: <semver string>
type: <simple or docker>
permissions: <list of strings>

# Required only if type == docker
docker:
  image: <name or image id>
  tag: <string, optional>
commands:
  <command_name>:
    executable: <string>
    options: <hash of option defs>
    rules: <list of rules>
    default_env: <hash of env vars>
  <command_name>:
    executable: <string>
    options: <hash of option defs>
    rules: <list of rules>
    default_env: <hash of env vars>
templates:
  <template_name>:
    provider: <slack or hipchat>
    contents: <literal template contents>
```

Regarding templates there are 3 supported use cases:
1. User inlines template literals directly in config.yaml.
`cogctl bundles deploy path/to/config.yaml`

2. User stores templates in a directory named 'templates' in the same directory as config.yaml.
   cogctl automatically reads those files and inlines them into config.yaml.
`cogctl bundles deploy path/to/config.yaml`

3. User stores templates in a directory either not named 'templates' or located somewhere
   other than the directory containing config.yaml.
`cogctl bundles deploy --templates=path/to/templates path/to/config.yaml`

For #2 and #3 cogctl expects the template directory to have the following layout:

```
templates
  |
  |---------slack
  |           |
  |           |------foo.mustache (template name is foo)
  |           |------bar.mustache (template name is bar)
  |
  |--------hipchat
              |
              |-----foo.mustache
              |-----bar.mustache
```

The final output that cogctl uploads to Cog:
```
# Format version
cog_bundle_version: 2

name: <string>
version: <semver string>
type: <simple or docker>
permissions: <list of strings>

# Required only if type == docker
docker:
  image: <name or image id>
  tag: <string, optional>
commands:
  <command_name>:
    executable: <string>
    options: <hash of option defs>
    rules: <list of rules>
    default_env: <hash of env vars>
  <command_name>:
    executable: <string>
    options: <hash of option defs>
    rules: <list of rules>
    default_env: <hash of env vars>
templates:
  - template
      name: foo
      provider: slack
      contents: <literal template contents>
  - template
      name: bar
      provider: slack
      contents: <literal template contents>
  - template
      name: foo
      provider: hipchat
      contents: <literal template contents>
  - template
      name: bar
      provider: hipchat
      contents: <literal template contents>
```

# Questions
* The yaml parser we use makes it easy to go from yaml to an elixir map, but it doesn't seem to make it easy to go back to yaml. Can we just encode the file as json and upload that to Cog?
  ** Yes
* Since we are using cogctl to upload configs would it be valuable to include spanner to do some validation before we upload?
  ** We can include it for now. If need be we can change it later.

# Plan
- [ ] Add a new action, `deploy` to `cogctl bundles`
