### ISSUE TITLE
Mount host directory into bundle

### ISSUE THREAD

**Issue by geowa4** [operable/cog#838]
At work, we use CoreOS's Fleet to schedule our containers across a few servers. Interaction with Fleet is via a unix socket `/var/run/fleet.sock`. I would like to build a standard Docker bundle to list, start, and stop units. To do that, I'll need the Relay to send the mount option to the container. I imagine a slight change to the `config.yaml` as follows.

Current:
```
docker:
  image: my/bundle
  tag: "0.1"
```

Proposed:
```
docker:
  image: my/bundle
  volumes:
    - /path/on/host:/path/on/container
  tag: "0.1"
```

**Comment by christophermaier** [comment]
This is done and available now on the `master` branch of both Cog and Relay. It will be available in the next release of Cog.

To bind mounts into the container you can do something like this:

```yaml
docker:
  image: my/bundle
  binds:
    - /path/on/host:/path/on/container
    - /another/host/path:/another/container/path
  tag: "0.1"
```

`binds` is a list of strings you would pass as values in `HostConfig -> Binds` in the `POST` body for the Docker [/containers/create](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/create-a-container) API endpoint

The relevant bit of that documentation for our purposes is quoted here:

`host_path:container_path` to bind-mount a host path into the container
`host_path:container_path:ro` to make the bind-mount read-only inside the container.
`volume_name:container_path` to bind-mount a volume managed by a volume plugin into the container.
`volume_name:container_path:ro` to make the bind mount read-only inside the container.
