### ISSUE TITLE
tutorial documentation fails on cog->relay network binding on OS X

### ISSUE THREAD

**Issue by lazzarello** [operable/cog#905]
I'm referencing the [v0.12 document](http://docs.operable.io/docs/installation)

Using the native OS X Docker app (which I'm new to but it appears to be running within a Linux VM)

```
$ docker info
Containers: 5
 Running: 3
 Paused: 0
 Stopped: 2
Images: 5
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 40
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge overlay null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.954 GiB
Name: moby
ID: P7M2:ORQV:N3S7:AJQB:QW4V:ZM3T:XVTH:X3IL:6CFC:47JX:VVLC:DLL7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 35
 Goroutines: 66
 System Time: 2016-08-06T23:13:25.533479136Z
 EventsListeners: 2
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

Bootstrapping works fine, Slack integration is fine, I can interact with the default bot bundles like `help` and `echo`.

I installed the EC2 bundle, configured it correctly and I get some error output.

```
An error has occurred.

At `2016-08-06T23:02:07Z`, @pizza initiated the following pipeline, assigned the unique ID `5ab046f709f44a448748e9976bc30d47`:
   `ec2-find --region="us-east-1"`

The specific error was:
   Whoops! An error occurred. No Cog Relays supporting the `mist` bundle are currently online
```

INTERESTING! Especially considering the bot identifies the following relays from the `help` command

```
mist:ec2-create
mist:ec2-destroy
mist:ec2-find
mist:ec2-state
mist:ec2-tags
mist:keypairs-list
mist:s3-bucket-acl
mist:s3-bucket-files
mist:s3-buckets
mist:vpc-list
```

I noticed an error from the docker-compose log output that might be interesting...

```
relay_1     | time="2016-08-06T23:12:53Z" level=error msg="Error connecting to tcp://localhost:1883." 
relay_1     | time="2016-08-06T23:12:53Z" level=info msg="Waiting 92 seconds before reconnecting." 
relay_1     | time="2016-08-06T23:14:25Z" level=error msg="Error connecting to tcp://localhost:1883." 
relay_1     | time="2016-08-06T23:14:25Z" level=info msg="Waiting 91 seconds before reconnecting." 
relay_1     | time="2016-08-06T23:15:56Z" level=error msg="Error connecting to tcp://localhost:1883." 
relay_1     | time="2016-08-06T23:15:56Z" level=info msg="Waiting 91 seconds before reconnecting." 
```

this keeps going as long as the relay container runs.

I also noticed the following active connections to port 1883 on localhost from the cog container, which the relay configuration is told to bind to localhost in the docker-compose.yml file.

```
$ docker exec -it $(docker-compose ps -q cog) netstat -an | grep 1883
...
tcp        0      0 127.0.0.1:35634         127.0.0.1:1883          ESTABLISHED 
tcp        0      0 127.0.0.1:35441         127.0.0.1:1883          ESTABLISHED 
tcp        0      0 127.0.0.1:36864         127.0.0.1:1883          ESTABLISHED 
tcp        0      0 127.0.0.1:1883          127.0.0.1:44570         ESTABLISHED 
tcp        0      0 127.0.0.1:1883          127.0.0.1:37488         ESTABLISHED 
tcp        0      0 127.0.0.1:36478         127.0.0.1:1883          ESTABLISHED 
tcp        0      0 127.0.0.1:1883          127.0.0.1:35634         ESTABLISHED 
tcp        0      0 127.0.0.1:37488         127.0.0.1:1883          ESTABLISHED 
tcp        0      0 127.0.0.1:46590         127.0.0.1:1883          ESTABLISHED 
tcp        0      0 127.0.0.1:33110         127.0.0.1:1883          ESTABLISHED 
tcp        0      0 127.0.0.1:44570         127.0.0.1:1883          ESTABLISHED 
tcp        0      0 127.0.0.1:43471         127.0.0.1:1883          ESTABLISHED 
tcp        0      0 127.0.0.1:1883          127.0.0.1:36478         ESTABLISHED 
tcp        0      0 127.0.0.1:38820         127.0.0.1:1883          ESTABLISHED 
tcp        0      0 127.0.0.1:1883          127.0.0.1:38820         ESTABLISHED 
tcp        0      0 127.0.0.1:1883          127.0.0.1:46187         ESTABLISHED
```

So the beam process is establishing a connection but when I try to connect from the relay container. It is refused.

```
$ docker exec -it $(docker-compose ps -q relay) telnet localhost 1883
telnet: can't connect to remote host (127.0.0.1): Connection refused
```

So, the relay container cannot communicate with the cog container, despite the cog container showing active connections to the beam process listening on port 1883.

I can help debug but I'm out of ideas outside of going into the source code, which I'm not ready for since this is a "getting started" tutorial.

**Comment by Shelton** [comment]
@lazzarello Thanks for submitting this issue + sorry for the delayed response. We've looked at this and have added it to our upcoming release. We hope to get this squared away soon!

**Comment by ChristopherBiscardi** [comment]
I've been using the following with "Docker for Mac" (It helped someone in slack, so might help people here too?)

```yaml
# For the sake of this example, you will need to have the following
# environment variables exported in your local environment:
#
#    * SLACK_API_TOKEN
#    * COG_HOST - this is not a Cog environment variable per se, but
#      one specifically for this docker-compose example. You should
#      set this to the host that cog can be accessed "from the
#      outside". If using docker-machine, for example, you could set
#      this to `docker-machine ip default`
#
# The Cog API will be available on port 80 of $COG_HOST, while
# triggers can be invoked on port 3000.
#
# To see all the environment variables that affect Cog's behavior,
# please see the online documentation at
#
#   * http://docs.operable.io/docs/cog-environment-variables
#   * http://docs.operable.io/docs/relay-environment-variables
version: '2'
services:
  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=cog
      - POSTGRES_PASSWORD=cog
    networks:
      - cog
  
  cog:
    image: operable/cog:0.12
    environment:
      - SLACK_API_TOKEN=$SLACK_API_TOKEN
      - COG_MQTT_HOST=0.0.0.0
      - DATABASE_URL=ecto://cog:cog@postgres:5432/cog
      # Overrides
      - COG_BOOTSTRAP_USERNAME=admin
      - COG_BOOTSTRAP_PASSWORD=changeme
      - COG_BOOTSTRAP_EMAIL_ADDRESS=admin@email.com
      - COG_BOOTSTRAP_FIRST_NAME=Cog
      - COG_BOOTSTRAP_LAST_NAME=Admin
      - COG_API_URL_HOST=cog
      - COG_API_URL_PORT=4000
      - COG_TRIGGER_URL_HOST=cog
      - COG_TRIGGER_URL_PORT=4001
      - COG_SERVICE_URL_HOST=cog
      - COG_SERVICE_URL_PORT=4002
      - RELAY_ID=00000000-0000-0000-0000-000000000000
      - RELAY_COG_TOKEN=supersecret
    ports:
      - 1883
      - 4000:4000
      - 4001:4001
      - 4002:4002
    entrypoint: /home/operable/cog/scripts/docker-start
    networks:
      - cog
  
  relay:
    image: operable/relay:0.12
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - RELAY_COG_REFRESH_INTERVAL=30s
      - RELAY_DOCKER_CLEAN_INTERVAL=1m
      - RELAY_COG_HOST=cog
      - RELAY_DYNAMIC_CONFIG_ROOT=/tmp/bundle_configs
      # Overrides
      - RELAY_ID=00000000-0000-0000-0000-000000000000
      - RELAY_COG_TOKEN=supersecret
    entrypoint: /usr/local/bin/relay
    networks:
      - cog
networks:
  cog:
    driver: bridge
```
